[tool.poetry]
name = "airflowdevi"
version = "0.1.0"
description = ""
authors = ["Matthias Vitt <matthias.vitt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
