version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.11"
        NODE_VERSION: "none"
    networks:
      - networkname
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: vscode
#    env_file: .env
networks:
 networkname:
   external:
     name: pickaxe